# Generated by Django 3.0.2 on 2021-07-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('companies', models.ManyToManyField(to='data_statistics.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('job_title', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='data_statistics.Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='data_statistics.Location')),
            ],
        ),
    ]
